project:
  type: website

website:
  # title: "My Portfolio"
  navbar:
    left:
      - href: index.qmd
        text: About
      - href: projects.qmd
        text: Academic Projects & Papers
format:
  html:
    theme: cosmo
    css: style.css
    toc: true

editor: visual

