---
title: "Academic Projects & Paper"
---

## 2025

### *Introduction to Data Science (STATS 0118)*

For the Final Project, its purpose was for us to take what we learned in class and apply it to a data analysis paper of our own choosing. By selecting and joining two datasets, we got to practice technical skills in R and formulate research questions and communicate insights through figures and text. Datasets could be chosen freely, with suggested sources including Kaggle, TidyTuesday, Google Dataset Search, WHO, GSS, CDC, or web scraping from reliable sites. In addition to these core requirements, we were required to complete at least two advanced challenges, such as working with time data using lubridate, web scraping with rvest, reshaping data with pivot_wider or pivot_longer, mapping with the sf package, or exploring other visualization techniques not covered in class.

<a href="STATS118-final.html" target="_blank">Open Link<a>

## 2024

### *Natural Language Processing (CSCI 0457)*

During the second half of the semester, we were tasked with completing a natural language processing (NLP) research project that synthesized the knowledge and tools we had explored in class, such as word embeddings, part-of-speech tagging with the Viterbi algorithm, and hate speech classification using BERT. The goal of this assignment was not to produce a contribution comparable to a published paper, but rather to immerse us in the research process. By carrying out each stage — from literature review and data collection to method design, evaluation, and ethical reflection — we were able to see how theoretical concepts translate into practical investigation. To further mirror professional standards in the field, the report was written in LaTeX using the ACL conference template, and findings were presented to the class during the final week.

<a href="CS457-final.pdf" target="_blank"> Open PDF</a>

### *Research Methods (PSYC 0202)*

In this Research Methods Project, students had the chance to apply scientific research methods to psychology. The project involved using quantitative methods to test hypotheses and draw conclusions about psychological topics. Over the course, we developed our own research proposals and study designs, culminating in a written report in APA format and a final presentation at the end of the semester.

<a href="PSYC202-final.pdf" target="_blank"> Open PDF</a> (Report)

<a href="PSYC202-final-poster.pdf"target="_blank">Open PDF</a> (Poster)
